$path = "c:\Users\PABLO\OneDrive\Desktop\PROYECTO EL CONDOR\subir github\calculadora_elcondor.html"
$content = Get-Content -Path $path -Raw -Encoding UTF8

$content = $content -replace 'CÃƒÂ³ndor', 'Cóndor'
$content = $content -replace 'TECNOLOGÃƒÂ A', 'TECNOLOGÍA'
$content = $content -replace 'ENERGÃƒÂ A', 'ENERGÍA'
$content = $content -replace 'UbicaciÃƒÂ³n', 'Ubicación'
$content = $content -replace 'TelÃƒÂ©fono', 'Teléfono'
$content = $content -replace 'InstalaciÃƒÂ³n', 'Instalación'
$content = $content -replace 'CaÃƒÂ±os', 'Caños'
$content = $content -replace 'CaÃƒÂ±erÃƒÂ­a', 'Cañería'
$content = $content -replace 'AislaciÃƒÂ³n', 'Aislación'
$content = $content -replace 'EstÃƒÂ©tico', 'Estético'
$content = $content -replace 'DesinstalaciÃƒÂ³n', 'Desinstalación'
$content = $content -replace 'TÃƒÂ©rmicas', 'Térmicas'
$content = $content -replace 'automÃƒÂ¡ticamente', 'automáticamente'
$content = $content -replace 'PlafÃƒÂ³n', 'Plafón'
$content = $content -replace 'CanalizaciÃƒÂ³n', 'Canalización'
$content = $content -replace 'MetÃƒÂ¡licas', 'Metálicas'
$content = $content -replace 'mÃƒÂ©nsulas', 'ménsulas'
$content = $content -replace 'sujeciÃƒÂ³n', 'sujeción'
$content = $content -replace 'bulonerÃƒÂ­a', 'bulonería'
$content = $content -replace 'aÃƒÂ©reo', 'aéreo'
$content = $content -replace 'LÃƒÂ­neas', 'Líneas'
$content = $content -replace 'IluminaciÃƒÂ³n', 'Iluminación'
$content = $content -replace 'CÃƒÂ¡maras', 'Cámaras'
$content = $content -replace 'CÃƒÂ¡mara', 'Cámara'
$content = $content -replace 'ViÃƒÂ¡ticos', 'Viáticos'
$content = $content -replace 'DÃƒÂ­as', 'Días'
$content = $content -replace 'Ã°Å¸â€œÅ ', '📊'
$content = $content -replace 'Ã°Å¸â€ Â¥', '🔥'
$content = $content -replace 'Ã¢Å¡Â¡', '⚡'
$content = $content -replace 'Ã¢â‚¬â€ ', '—'
$content = $content -replace 'ÃƒÂ³', 'ó'
$content = $content -replace 'ÃƒÂ©', 'é'
$content = $content -replace 'ÃƒÂ­', 'í'
$content = $content -replace 'ÃƒÂ¡', 'á'
$content = $content -replace 'ÃƒÂº', 'ú'
$content = $content -replace 'ÃƒÂ±', 'ñ'
$content = $content -replace 'ÃƒÂ ', 'í'
$content = $content -replace 'Ã‚Â·', '·'
$content = $content -replace 'ÃƒÂ', 'í'

Set-Content -Path $path -Value $content -Encoding UTF8
Write-Host "Done"
